### ISSUE TITLE
eslint no redeclare

### ISSUE THREAD

**Issue by nopeless** [unjs/eslint-config#4]
This eslint config appears to not properly support typescript specifically eslint no redeclare

I believe this is a quick fix

```
function test(a: string): string;
function test (b: string): string {
  return "string";
}

```

**Comment by pi0** [comment]
We need to disable eslint rule and enable typescript one. https://typescript-eslint.io/rules/no-redeclare/ feel free to make PR

**Comment by nopeless** [comment]
@pi0 Mind if I add some more typescript-eslint rules along these?

**Comment by pi0** [comment]
should be fixed in last release. Feel free to open PR directly for any other suggestions @nopeless 👍🏼
