### ISSUE TITLE
Style Preset with ESLint Stylistic

### ISSUE THREAD

**Issue by pi0** [unjs/eslint-config#9]
(Traditionally?) Linters and Formatters are two different concepts and for this reason, i chose to make base eslint-config be linter only.

However i (at least personally) am happy with Prettier as a style formatter for most of the cases, i think [ESLint Stylistic](https://eslint.style/) (made by @antfu) has great potential to be a less annoying standard formatter and alternative.

I am thinking to play with a `unjs-eslint-config/stylistic` preset that extends it (and as much as possible, configure rules to be semi-compatible with existing prettier ones to reduce ecosystem migration cost and keep it closer)

**Comment by antfu** [comment]
It's a still very rough idea, but we were thinking of providing a few presets of stylistic rules right in the plugin, for example, `minimal`(no-semi + spaces + single-quote) and `standard` (semi + tab + double-qoutes) (name to be discussed) as a foundation for higher-level integration like unjs eslint-config.

**Comment by pi0** [comment]
That would be even better with standard. Are you considering a `prettier` as well? That's what i mainly want to have something is _compatible_ with prettier conventions (it uses spaces i guess for example)

**Comment by antfu** [comment]
Yeah, for sure. We have plenty of room to discuss.

**Comment by pi0** [comment]
Testing against nitro and rc.7, prettier compatibility required disabling multiple rules additionally to config:

```js
  stylistic.configs.customize({
    // prettier compatible
    indent: 2,
    quotes: "double",
    semi: true,
    commaDangle: "always-multiline",
    arrowParens: true,
    braceStyle: "1tbs",
    quoteProps: "as-needed",
    blockSpacing: true,
  }),
  {
    rules: {
      "@stylistic/indent": 0,
      "@stylistic/operator-linebreak": 0,
      "@stylistic/no-tabs": 0,
      "@stylistic/indent-binary-ops": 0,
      "@stylistic/quotes": 0,
      "@stylistic/keyword-spacing": 0,
      "@stylistic/space-in-parens": 0,
    },
  },
```

---

Honestly, i really love the idea of merging linter and formatting and stylistic seemed a really good opportunity but honestly, today seems too hacky and I neither have time to maintain compact nor want to imply pressure on stylistic project for something is non goal.

----

Some strange issues:

<img width="523" alt="image" src="https://github.com/unjs/eslint-config/assets/5158436/16ad5d50-6fe5-4e3d-abc0-dc7b326c0a08">



<img width="505" alt="image" src="https://github.com/unjs/eslint-config/assets/5158436/13d2e106-e516-40d6-946f-c8301b0cb688">
